jee/src/main/java/bean/Activity.java
package bean;

import java.util.Date;

import utils.MyUtils;

public class Activity {

	
	public enum DbNames{
		ID				("Id", 0),
		DATE			("Date", 1),
		DURATION		("Duration" , 2),
		COMMENT			("Comment" , 3),
		MEMBER_ID		("MemberId" , 4),
		ASSIGMENT_ID	("AssigmentId" , 5);
		
		
		private final String colName;
		private final int colNum;
		DbNames(String name, int num){
			colName = name;
			colNum = num;
		}
		public String getColName(){
			return colName;
		}
		
		public int getColNum(){
			return colNum;
		}
	}

	private int id;
	private Date date;
	private int duration;
	private String comment;
	private int memberId;
	private int assigmentId;
	
	private int taskId;
	private Employee employee;
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public Date getDate() {
		return date;
	}
	public String getDateView() {
		return MyUtils.getDateString(date);
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public int getDuration() {
		return duration;
	}
	public void setDuration(int duration) {
		this.duration = duration;
	}
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	public int getMemberId() {
		return memberId;
	}
	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}
	public int getAssigmentId() {
		return assigmentId;
	}
	public void setAssigmentId(int assigmentId) {
		this.assigmentId = assigmentId;
	}
	public int getTaskId() {
		return taskId;
	}
	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}
	public Employee getEmployee() {
		return employee;
	}
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}
	
}

jee/src/main/java/bean/Task.java
package bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.apache.commons.fileupload.FileItem;

import utils.MyUtils;

public class Task {
	public enum DbNames{
		ID			("Id", 0),
		PROJECT_ID	("ProjectId", 1),
		DESCRIPTION	("Description" , 2),
		PSD			("Psd" , 3),
		PDD			("Pdd" , 4),
		ASD			("Asd" , 5),
		ADD			("Add" , 6),
		STATUS_ID	("StatusId" , 7);
		
		private final String colName;
		private final int colNum;
		DbNames(String name, int num){
			colName = name;
			colNum = num;
		}
		public String getColName(){
			return colName;
		}
		
		public int getColNum(){
			return colNum;
		}
	}
	
	private int id;
	private int projectId;
	private String description;
	private Date psd;
	private Date pdd;
	private Date asd;
	private Date add;
	private Status status;
	
	Employee assignedEmployee;
	List <Attachment> attachments = new ArrayList<Attachment>();
	List <FileItem> files = new ArrayList<FileItem>();;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getProjectId() {
		return projectId;
	}
	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Date getPsd() {
		return psd;
	}
	public String getPsdView() {
		return MyUtils.getDateString(psd);
	}
	public void setPsd(Date psd) {
		this.psd = psd;
	}
	public Date getPdd() {
		return pdd;
	}
	public String getPddView() {
		return MyUtils.getDateString(pdd);
	}
	public void setPdd(Date pdd) {
		this.pdd = pdd;
	}
	public Date getAsd() {
		return asd;
	}
	public String getAsdView() {
		return MyUtils.getDateString(asd);
	}
	public void setAsd(Date asd) {
		this.asd = asd;
	}
	public Date getAdd() {
		return add;
	}
	public String getAddView() {
		return MyUtils.getDateString(add);
	}
	public void setAdd(Date add) {
		this.add = add;
	}
	public Status getStatus() {
		return status;
	}
	public void setStatus(Status status) {
		this.status = status;
	}
	
	public Employee getAssignedEmployee() {
		return assignedEmployee;
	}
	public void setAssignedEmployee(Employee assignedEmployee) {
		this.assignedEmployee = assignedEmployee;
	}
	
	public void addAttachment(Attachment attachment) {
		attachments.add(attachment);
	}

	public List<Attachment> getAttachments() {
		return attachments;
	}
	
	public void addFiles(List<FileItem> files) {
		this.files = files;
	}
	
	public List<FileItem> getFiles() {
		return files;
	}
}

jee/src/main/java/controllers/ActivityListController.java
package controllers;

import java.io.IOException;
import java.util.List;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
//import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import DAOInterfaces.IActivityDAO;
import bean.Activity;
import bean.Config;
import bean.Constants;
import exceptions.DaoException;
import exceptions.ValidateException;
import factories.modelFactory;
import validators.IdValidator;


/**
 * Servlet implementation class IndexController
 */
//@WebServlet(urlPatterns = {"/index","/"})
public class ActivityListController extends HttpServlet {
	private static final long serialVersionUID = 1L;

    /**
     * Default constructor. 
     */
    public ActivityListController() {
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub

	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		IActivityDAO activityDAO = modelFactory.getActivityModel();

		try{
			IdValidator validator = new IdValidator("taskId");
			int taskId = (Integer) validator.validate(request);

			List <Activity> activityList = activityDAO.getActivitiesForTask(taskId);
			
			request.setAttribute("activityList", activityList);
			
			RequestDispatcher rd = request.getRequestDispatcher(Config.TEMPLATE_PATH +"list_activities.jsp");
		    rd.forward(request, response);
		} catch (ValidateException e){
			//System.out.println(e);
			request.setAttribute(Constants.PAR_NAME_STATUS_ERROR, e.getMessage());
			RequestDispatcher rd = request.getRequestDispatcher(Config.TEMPLATE_ERROR_AJAX);
			rd.forward(request, response);
		} catch (DaoException e){
			//System.out.println(e);
			request.setAttribute(Constants.PAR_NAME_STATUS_ERROR, e.getMessage());
			RequestDispatcher rd = request.getRequestDispatcher(Config.TEMPLATE_ERROR_AJAX);
			rd.forward(request, response);
		}
	}

}

jee/src/main/java/controllers/AddReportController.java
package controllers;

import static logger.LoggerClass.LOGGER;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import DAOInterfaces.ITaskDAO;
import bean.Activity;
import bean.Config;
import bean.Constants;

import exceptions.DaoException;
import exceptions.ValidateException;
import factories.modelFactory;
import utils.MyUtils;
import validators.ActivityFormValidator;
import validators.IValidator;
import validators.IdValidator;

/**
 * Servlet implementation class IndexController
 */
//@WebServlet(urlPatterns = {"/index","/"})
public class AddReportController extends HttpServlet {
	private static final long serialVersionUID = 1L;

    /**
     * Default constructor. 
     */
    public AddReportController() {
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub

		try{
			IValidator validator = new IdValidator("taskId");
			int taskId = (Integer) validator.validate(request);

			request.setAttribute("taskId", taskId);
			
			RequestDispatcher rd = request.getRequestDispatcher(Config.TEMPLATE_PATH +"forms/reportForm.jsp");
			rd.forward(request, response);
		} catch (ValidateException e){
			request.setAttribute("error", "wrong format");
			RequestDispatcher rd = request.getRequestDispatcher(Config.TEMPLATE_ERROR_AJAX);
			rd.forward(request, response);
		} 
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		ITaskDAO taskDAO = modelFactory.getTaskModel();

		Map<String, String> options = new HashMap<String, String>();
		
		LOGGER.info("Trying add report");
		try{
			IValidator validateForm = new ActivityFormValidator();
			Activity activity = (Activity) validateForm.validate(request);
			
			taskDAO.addActivity(activity);
			
			options.put(Constants.PAR_NAME_STATUS, Constants.PAR_NAME_STATUS_OK);

		} catch (ValidateException e){
			options.put(Constants.PAR_NAME_STATUS, Constants.PAR_NAME_STATUS_ERROR);
			options.put(Constants.PAR_NAME_MESSAGE, e.getMessage());

		} catch(DaoException e){
			options.put(Constants.PAR_NAME_STATUS, Constants.PAR_NAME_STATUS_ERROR);
			options.put(Constants.PAR_NAME_MESSAGE, e.getMessage());

		}
		
		MyUtils.sendWithJSON(options, response);
		
	}

}

jee/src/main/java/controllers/DashboardActivityListController.java
package controllers;

import java.io.IOException;
import java.util.List;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import DAOInterfaces.IActivityDAO;
import bean.Activity;
import bean.Config;
import bean.Constants;
import exceptions.DaoException;
import exceptions.ValidateException;
import factories.modelFactory;
import pagination.Paginator;
import validators.IValidator;
import validators.IdValidator;


/**
 * Servlet implementation class IndexController
 */
//@WebServlet(urlPatterns = {"/index","/"})
public class DashboardActivityListController extends HttpServlet {
	private static final long serialVersionUID = 1L;

    /**
     * Default constructor. 
     */
    public DashboardActivityListController() {
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub

	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		IActivityDAO activityDAO = modelFactory.getActivityModel();

		try{
			IValidator validator = new IdValidator("pageNum");
			int pageNumActivity = (Integer) validator.validate(request);
			pageNumActivity++; // setNextPage
			int activityCount  = Config.COUNT_ACTIVITIES_PER_PAGE;

			List <Activity> activityList = activityDAO.getAllActivities(activityCount*pageNumActivity, 0);
			int activityAllCount  = activityDAO.getCountAllRows();
			
			Paginator paginatorActivity = new Paginator(activityAllCount, activityCount, pageNumActivity);
			request.setAttribute("paginatorActivity", paginatorActivity);
			
			request.setAttribute("activityList", activityList);
			
			RequestDispatcher rd = request.getRequestDispatcher(Config.TEMPLATE_PATH +"list_activities.jsp");
			rd.forward(request, response);

		} catch (DaoException  e){
			//System.out.println(e);
			request.setAttribute(Constants.PAR_NAME_STATUS_ERROR, e.getMessage());
			RequestDispatcher rd = request.getRequestDispatcher(Config.TEMPLATE_ERROR_AJAX);
			rd.forward(request, response);
			
		} catch (ValidateException e){
			//System.out.println(e);
			request.setAttribute(Constants.PAR_NAME_STATUS_ERROR, e.getMessage());
			RequestDispatcher rd = request.getRequestDispatcher(Config.TEMPLATE_ERROR_AJAX);
			rd.forward(request, response);
		} 
	}

}

jee/src/main/java/controllers/DashboardController.java
package controllers;

import java.io.IOException;
import java.util.List;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import DAOInterfaces.IActivityDAO;
import DAOInterfaces.ITaskDAO;
import bean.Activity;
import bean.Config;
import bean.Constants;
import bean.Employee;
import bean.Task;
import factories.modelFactory;
import pagination.Paginator;


/**
 * Servlet implementation class DashBoardController
 */
public class DashboardController extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public DashboardController() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		
		Employee employee = (Employee) session.getAttribute(Constants.SESSTION_ATTR_NAME_EMPLOYEE); 
		
		ITaskDAO taskDAO = modelFactory.getTaskModel();
		IActivityDAO activityDAO = modelFactory.getActivityModel();
		
		int pageNumTask = 1; // default number of page 
		int taskCount  = Config.COUNT_TASK_PER_PAGE;
		List <Task> taskList = taskDAO.getTasks(employee.getId(), (pageNumTask-1)*taskCount, taskCount);
		int taskAllCount  = taskDAO.getCountAllRows();

		Paginator paginatorTask = new Paginator(taskAllCount, taskCount, pageNumTask);
		request.setAttribute("paginator", paginatorTask);
		
		int pageNumActivity = 1; // default number of page activity
		int activityCount  = Config.COUNT_ACTIVITIES_PER_PAGE;
		List <Activity> activityList = activityDAO.getAllActivities(activityCount,activityCount*(pageNumActivity-1));
		int activityAllCount  = activityDAO.getCountAllRows();
		
		Paginator paginatorActivity = new Paginator(activityAllCount, activityCount, pageNumActivity);
		
		request.setAttribute("paginatorActivity", paginatorActivity);
		request.setAttribute("activityList", activityList);
		request.setAttribute("taskList", taskList);
		request.setAttribute(Constants.PAR_NAME_PAGENAME, "dashboard.jsp");		
		
		RequestDispatcher rd = request.getRequestDispatcher(Config.TEMPLATE_MAIN);
		rd.forward(request, response);
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		
	}

}

jee/src/main/java/controllers/EmployeeOnProjectController.java
package controllers;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.google.gson.Gson;

import DAOInterfaces.IEmployeeDAO;
import bean.Constants;
import bean.Employee;
import exceptions.DaoException;
import factories.modelFactory;



/**
 * Servlet implementation class IndexController
 */
//@WebServlet(urlPatterns = {"/index","/"})
public class EmployeeOnProjectController extends HttpServlet {
	private static final long serialVersionUID = 1L;

    /**
     * Default constructor. 
     */
    public EmployeeOnProjectController() {
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		
		Map<String, String> options = new HashMap<String, String>();
			
		IEmployeeDAO employeeDAO = modelFactory.getEmployeeModel();
		try{
			int idProj = Integer.parseInt(request.getParameter("projId"));
			List<Employee> listEmployee = employeeDAO.getEmployeesFromProject(idProj);
			StringBuilder str = new StringBuilder();
			
			for (Employee e : listEmployee){
				str.append(new Gson().toJson(e));
			}
			
			response.setContentType(Constants.CONTENT_TYPE_JSON);
		    response.setCharacterEncoding(Constants.ENCODING_UTF8);
		    response.getWriter().write(new Gson().toJson(listEmployee));

		} catch (NumberFormatException e){
			options.put(Constants.PAR_NAME_STATUS, Constants.PAR_NAME_STATUS_ERROR);
			options.put(Constants.PAR_NAME_MESSAGE, e.getMessage());

		} catch(DaoException e){
			options.put(Constants.PAR_NAME_STATUS, Constants.PAR_NAME_STATUS_ERROR);
			options.put(Constants.PAR_NAME_MESSAGE, e.getMessage());

		}
		
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
	}

}

jee/src/main/webapp/WEB-INF/admin.jsp



<div class="row">
	<div class="col-sm-1"></div>
	
	<div class="col-sm-5">
		<div id="addEmployee">Add employee <span class="glyphicon glyphicon-plus-sign"></span></div>
		<div class="adminUsersList">
		
		<%@ include  file="admin_list_employee.jsp" %>
		</div>
	</div>




	<div class="col-sm-5">
		<div id="addProject">Add project <span class="glyphicon glyphicon-plus-sign"></span></div>
		<div class="adminProjectsList">
		
		<%@ include  file="admin_list_projects.jsp" %>
		</div>
	</div>

	<div class="col-sm-1"></div>
</div>
<div style="clear:both"></div>



jee/src/main/webapp/WEB-INF/admin_list_employee.jsp



<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>


<c:if test="${not empty listEmployees}">
<table class="table">
<c:forEach items="${listEmployees}" var="employee" varStatus="loop">
        <tr>
            <td>${loop.count}</td>
            <td>${employee.firstName}</td>
            <td>${employee.lastName}</td>
            <td>${employee.login}</td>
            <td>${employee.position.name}</td>
            <td><span class="editEmployee" rowId="${employee.id}" >Edit <span class="glyphicon glyphicon-edit"></span></span></td>
            <td><span class="deleteEmployee" rowId="${employee.id}" >Delete <span class="glyphicon glyphicon-trash"></span></span></td>
        </tr>
    </c:forEach>
</div>
</table>
</c:if>

<c:if test="${empty listEmployees}">
no employees
</c:if>


jee/src/main/webapp/WEB-INF/admin_list_projects.jsp



<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>


<c:if test="${not empty listProjects}">
<table class="table">
<c:forEach items="${listProjects}" var="project" varStatus="loop">
        <tr>
            <td>${loop.count}</td>
            <td>${project.name}</td>
            <td>${project.description}</td>
            
            <td><span class="editProject" rowId="${project.id}" >Edit <span class="glyphicon glyphicon-edit"></span></span></td>
            <td><span class="deleteProject" rowId="${project.id}" >Delete <span class="glyphicon glyphicon-trash"></span></span></td>
        </tr>
    </c:forEach>
</div>
</table>
</c:if>

<c:if test="${empty listProjects}">
no projects
</c:if>



jee/src/main/webapp/WEB-INF/error.jsp
${error}

jee/src/main/webapp/WEB-INF/footer.jsp
        <div id="popUp">
		    <div class="before"></div>
		    <div class="content">
		    
		    </div>
		</div>


</div>
    </div>
<div class="footer">
created by Lapanau Aliaksei 2016
</div>
</body>
</html>

jee/src/main/webapp/WEB-INF/header.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<?xml version="1.0" encoding="utf-8" ?>
<%@ page language="java" contentType="text/html; charset=utf-8"
    pageEncoding="utf-8"%>

<!doctype html>
<html lang="en">
<head>
    <title>jee</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content=''>
    <meta name="description" content=''>
    <link href="<c:url value="/resources/css/normalize.css" />" rel="stylesheet" type="text/css" />
    <!-- <link href="./css/styles.css" rel="stylesheet" type="text/css" /> -->

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- --><link href="<c:url value="/resources/css/styles.less" />" rel="stylesheet/less" type="text/css" />
    <script src="<c:url value="/resources/js/less/less.min.js"/>" type="text/javascript"></script>
    
    <script src="<c:url value="/resources/js/jquery/jquery-1.7.1.min.js"/>" type="text/javascript"></script>
    <script src="<c:url value="/resources/js/myscript.js"/>" type="text/javascript"></script>
    
    <link href="<c:url value="/resources/bootstrap/css/bootstrap.min.css"/>" rel="stylesheet" type="text/css"  />
    <script src="<c:url value="/resources/bootstrap/js/bootstrap.min.js"/>" type="text/javascript" ></script>
    
    <link href="<c:url value="/resources/datepicker/css/datepicker.css"/>" rel="stylesheet" type="text/css"  />
    <script src="<c:url value="/resources/datepicker/js/bootstrap-datepicker.js"/>" type="text/javascript" ></script>
    
</head>


</head>
<body>
<div class="main">

        <div class="header">
        
        
        
        <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      
      <a class="navbar-brand" href="<c:url value="/"/>">JEE task</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
        
      <ul class="nav navbar-nav">
        <c:if test="${sessionScope.Role.showDashboardProject}">
        
                
                <li><a href="<c:url value="/dashboard"/>">Dashboard</a></li>
                <li class="dropdown"><a id="myProjectsBtn" href="#"  class="dropdown-toggle">Projects<span class="caret"></span></a>
                     <ul class="dropdown-menu"></ul> 
                </li>
                <c:if test="${sessionScope.Role.allowTaskCreate}">
                    <li><a href="#" id="taskNewBtn">task add</a></li>
                </c:if>
        </c:if>
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <c:if test="${not empty sessionScope.Employee}">
            <li><a href="<c:url value="/logout"/>" id="logoutBtn">Logout ${sessionScope.Employee.login}</a></li>
        </c:if>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
        
        
        
        </div>
        <div class="cont">
        <div class="alert alert-danger" id="errorMsg">
		<c:if test="${not empty errorMessage}">
			<c:out value="${errorMessage}"/>
			</c:if>
		</div>

jee/src/main/webapp/WEB-INF/list_activities.jsp



<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>


<c:if test="${not empty activityList}">
    <c:forEach items="${activityList}" var="activity">
        <div class="activityBox">
            <div class="activityHeader">
	            <div class="activityEmployee">${activity.employee.firstName} ${activity.employee.lastName} </div>
		        <div class="activityDate">${activity.dateView}</div> 
	        </div>
	        <div class="activityComment">${activity.comment}</div>
        </div>
    </c:forEach>
    <c:if test="${not empty paginatorActivity && paginatorActivity.countPages != paginatorActivity.currentPage}">
        <div class="loadMoreActivitiesBtn btn btn-primary" pageNum="${paginatorActivity.currentPage}">More activities</div>
    </c:if>
</c:if>

<c:if test="${empty activityList}">
no activities
</c:if>



jee/src/main/webapp/WEB-INF/list_tasks.jsp



<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<c:if test="${not empty taskList}">
    <div class="taskListBox">

	<c:forEach items="${taskList}" var="task" varStatus="loop">
	
		<div class="row taskItem">
		  <div class="col-sm-1"><div class="counter">${loop.count+(paginator.currentPage-1)*paginator.countElementsOnPage}</div></div>
		  <div class="description col-sm-7"><a href="task?taskId=${task.id}"> ${task.description} </a></div>
		  <div class="status col-sm-2">${task.status.name}</div>
		  <div class="psd col-sm-2">${task.psdView}</div>
		</div>
	</c:forEach>
	</div>	
		
		<c:if test="${paginator.showPaginator}">
	<nav class="paginator">
		<ul class="pagination pagination-sm">
			<c:forEach var="pageNum" begin="1" end="${paginator.countPages}">
				<c:choose>
					<c:when test="${pageNum != paginator.currentPage}"><li class="pageNum" pageNum="${pageNum}"><a href="#">${pageNum}</a></li></c:when>
					<c:otherwise><li class="pageNum active" pageNum="${pageNum}"><a href="#">${pageNum}</a></li></c:otherwise>
				
				</c:choose>
			</c:forEach>
		</ul>
	</nav>
	</c:if>
</c:if>

<c:if test="${empty taskList}">
no tasks
</c:if>



jee/src/main/webapp/WEB-INF/login.jsp

<div class="loginForm">
<%@ include  file="forms/loginForm.jsp" %>
</div>



jee/src/main/webapp/WEB-INF/main.jsp
Activity stream

Nazna4ennie taski

jee/src/main/webapp/WEB-INF/main_template.jsp
<%@ include  file="header.jsp" %>

<c:if test="${not empty pagename}">
  <jsp:include page='${pagename}' flush="true"/>
 </c:if>

<%@ include  file="footer.jsp" %>

jee/src/main/webapp/WEB-INF/project.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<div class="row">
<div class="col-sm-2"></div>
<div class="col-sm-8">
	
	
<h2>${project.name}</h2>
<p>${project.description}</p>

<h3>Members</h3>
<table class="table table-bordered">
<c:forEach var="member" items="${project.members}" varStatus="status">
<tr>
<td>${member.key.firstName} ${member.key.lastName}</td>
<td> ${member.value.name}</td>
</tr>    
</c:forEach>
</table>
		</div>
		<div class="col-sm-2"></div>
</div>